//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyWords
    {
        public int id { get; set; }
        public string word { get; set; }
        public Nullable<int> webSiteId { get; set; }
        public int count { get; set; }
    
        public virtual WebSites WebSites { get; set; }
    }
}
