//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsToEmailDBEntities : DbContext
    {
        public NewsToEmailDBEntities()
            : base("name=NewsToEmailDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categories> Categories { get; set; }
        public DbSet<FiltersCategories> FiltersCategories { get; set; }
        public DbSet<KeyWords> KeyWords { get; set; }
        public DbSet<Livescores> Livescores { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<UsedEmails> UsedEmails { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersWebsites> UsersWebsites { get; set; }
        public DbSet<WebSites> WebSites { get; set; }
    }
}
