//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersWebsite
    {
        public int userId { get; set; }
        public int webSiteId { get; set; }
        public System.DateTime validUntil { get; set; }
        public bool isSelected { get; set; }
        public int id { get; set; }
        public Nullable<System.DateTime> lastSendDate { get; set; }
        public Nullable<int> lastSendNewsId { get; set; }
    
        public virtual User User { get; set; }
        public virtual WebSite WebSite { get; set; }
    }
}
