//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.FiltersCategories = new HashSet<FiltersCategories>();
            this.Livescores = new HashSet<Livescores>();
            this.UsedEmails = new HashSet<UsedEmails>();
            this.UsersWebsites = new HashSet<UsersWebsites>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public bool isEnabled { get; set; }
        public string password { get; set; }
        public Nullable<short> sendNewsHour { get; set; }
        public bool convertCyrlicToLatin { get; set; }
        public Nullable<int> sizeLimit { get; set; }
        public short webSitesMaxNumber { get; set; }
        public bool recieveFile { get; set; }
    
        public virtual ICollection<FiltersCategories> FiltersCategories { get; set; }
        public virtual ICollection<Livescores> Livescores { get; set; }
        public virtual ICollection<UsedEmails> UsedEmails { get; set; }
        public virtual ICollection<UsersWebsites> UsersWebsites { get; set; }
    }
}
