//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLBettingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Betline
    {
        public Betline()
        {
            this.PlacedBets = new HashSet<PlacedBet>();
        }
    
        public int BetlineId { get; set; }
        public double stakeRangeMin { get; set; }
        public double stakeRangeMax { get; set; }
        public double initialProfitPerBet { get; set; }
        public double profitPerBet { get; set; }
        public bool lastBetLost { get; set; }
        public bool isActive { get; set; }
        public string currencyCode { get; set; }
        public Nullable<int> Filter_FilterId { get; set; }
        public string lastPlacedBetId { get; set; }
        public string algorithmName { get; set; }
        public string betType { get; set; }
        public string betlineName { get; set; }
        public Nullable<decimal> ballance { get; set; }
    
        public virtual ICollection<PlacedBet> PlacedBets { get; set; }
        public virtual Filter Filter { get; set; }
    }
}
