//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLBettingApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BFDBLEntities1 : DbContext
    {
        public BFDBLEntities1()
            : base("name=BFDBLEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Betline> Betlines { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<PlacedBet> PlacedBets { get; set; }
        public DbSet<Filter> Filters { get; set; }
    }
}
