//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLBettingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public Filter()
        {
            this.Betlines = new HashSet<Betline>();
        }
    
        public int FilterId { get; set; }
        public string eventTypes { get; set; }
        public Nullable<System.DateTime> fromEventDate { get; set; }
        public Nullable<System.DateTime> toEventDate { get; set; }
        public bool isInPlay { get; set; }
        public Nullable<bool> isBSP { get; set; }
        public Nullable<byte> exchangeId { get; set; }
        public string countryCodes { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string marketTypes { get; set; }
        public int runnersMin { get; set; }
        public int runnersMax { get; set; }
        public int winnersMin { get; set; }
        public int winnersMax { get; set; }
        public Nullable<double> totalAmountMatchedMin { get; set; }
        public Nullable<double> totalAmountMatchedMax { get; set; }
        public string marketNames { get; set; }
        public string sortedOrdersMatchOdds { get; set; }
        public string sortedOrdersCorrectScore { get; set; }
        public Nullable<byte> maxBetsCount { get; set; }
        public Nullable<int> maxAmmountIncremented { get; set; }
        public Nullable<short> goalDifferenceMin { get; set; }
        public Nullable<short> goalDifferenceMax { get; set; }
    
        public virtual ICollection<Betline> Betlines { get; set; }
    }
}
