//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ValueOfPayment { get; set; }
        public string CurrencyOfPayment { get; set; }
    }
}
