//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBetApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public int MarketId { get; set; }
        public string MarketName { get; set; }
        public string MarketType { get; set; }
    }
}
