//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWCREWSERV
    {
        public int ID { get; set; }
        public Nullable<int> CWCREW_ID { get; set; }
        public Nullable<int> VSL_ID { get; set; }
        public Nullable<int> CWPRANK_ID { get; set; }
        public Nullable<int> CWPAITIOL_ID { get; set; }
        public Nullable<System.DateTime> DATEE { get; set; }
        public Nullable<System.DateTime> DATED { get; set; }
        public string REM1 { get; set; }
        public string REM2 { get; set; }
        public string CUR { get; set; }
        public Nullable<short> FL_OTHER { get; set; }
        public Nullable<short> FL_PASSEG { get; set; }
        public Nullable<System.DateTime> STARTING_DT { get; set; }
        public Nullable<System.DateTime> ARVD_HOME_DT { get; set; }
        public Nullable<System.DateTime> DATEIN { get; set; }
        public Nullable<int> USERIN_ID { get; set; }
        public Nullable<System.DateTime> DATEUPD { get; set; }
        public Nullable<int> USERUPD_ID { get; set; }
        public Nullable<short> FL_MGSERV { get; set; }
        public Nullable<int> PORTE_ID { get; set; }
        public Nullable<int> PORTD_ID { get; set; }
        public Nullable<System.DateTime> DATE_UPD { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
        public Nullable<short> FL_PREP { get; set; }
        public Nullable<double> LARGE_ADVANCE { get; set; }
        public Nullable<int> OLD_ID { get; set; }
        public Nullable<int> CWRHSCHED_ID { get; set; }
        public Nullable<int> FL_RHERR { get; set; }
        public Nullable<System.DateTime> PROP_DT { get; set; }
        public Nullable<short> FL_PROMOT { get; set; }
        public Nullable<int> PRV_RANK_ID { get; set; }
        public Nullable<double> ADVANCE_AMNT { get; set; }
    }
}
