//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWCREW
    {
        public int ID { get; set; }
        public string CODE { get; set; }
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string FATHERNAME { get; set; }
        public string MOTHERNAME { get; set; }
        public string WIFENAME { get; set; }
        public Nullable<short> CHILD_NUM { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIPCODE { get; set; }
        public string COUNTRY { get; set; }
        public string TELEPHONE1 { get; set; }
        public string TELEPHONE2 { get; set; }
        public string EMAIL { get; set; }
        public string BRTH_PLC { get; set; }
        public Nullable<System.DateTime> BRTH_DT { get; set; }
        public string RECOMMENDED { get; set; }
        public string NEXTOFKIN { get; set; }
        public string NEXTADDRESS { get; set; }
        public string NEXTCITY { get; set; }
        public string NEXTZIP { get; set; }
        public string NEXTTEL { get; set; }
        public string RELATION { get; set; }
        public string PSPRT_NO { get; set; }
        public string PSPRT_PLACE { get; set; }
        public Nullable<System.DateTime> PSPRT_ISSUE { get; set; }
        public Nullable<System.DateTime> PSPRT_EXPIRY { get; set; }
        public string SB_NO { get; set; }
        public string SB_PLACE { get; set; }
        public Nullable<System.DateTime> SB_ISSUE { get; set; }
        public Nullable<System.DateTime> SB_EXPIRY { get; set; }
        public Nullable<int> FL_MARITAL { get; set; }
        public string REMARKS { get; set; }
        public Nullable<int> CWPNATION_ID { get; set; }
        public Nullable<int> CWPRELIGION_ID { get; set; }
        public Nullable<int> CWPRANK_ID { get; set; }
        public Nullable<System.DateTime> DATEIN { get; set; }
        public Nullable<int> USERIN_ID { get; set; }
        public Nullable<System.DateTime> DATEUPD { get; set; }
        public Nullable<int> USERUPD_ID { get; set; }
        public Nullable<short> FL_ONBOARD { get; set; }
        public string DOC_DIR_NAME { get; set; }
        public string ATCH_DIR { get; set; }
        public string ATCH_REM { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
        public Nullable<System.DateTime> DATE_UPD { get; set; }
        public Nullable<short> RLS_NO { get; set; }
        public Nullable<short> FL_CHNG { get; set; }
        public Nullable<short> FL_SENT { get; set; }
        public Nullable<short> FL_REXST { get; set; }
        public string FL_FRNG { get; set; }
        public string LASTNAME_GR { get; set; }
        public string FIRSTNAME_GR { get; set; }
        public string FATHERNAME_GR { get; set; }
        public Nullable<short> FL_USE { get; set; }
        public string SIZE_POLO { get; set; }
        public string SIZE_PANTS { get; set; }
        public string SIZE_OVERALL { get; set; }
        public string SIZE_WINTER { get; set; }
        public string SIZE_TSHIRT { get; set; }
        public string SIZE_SHOES { get; set; }
        public string SIZE_CATER { get; set; }
        public string BRTH_PLC_GR { get; set; }
        public string MIDDLENAME { get; set; }
        public string PAG_NO { get; set; }
        public string HEALTH_NO { get; set; }
        public string SSS_NO { get; set; }
        public string SKYPE_ACCOUNT { get; set; }
        public string FB_ACCOUNT { get; set; }
        public Nullable<System.DateTime> TRM_DATE { get; set; }
        public Nullable<short> FL_TRM_REASON { get; set; }
    }
}
