//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWRESTHR
    {
        public int ID { get; set; }
        public Nullable<int> VSL_ID { get; set; }
        public Nullable<System.DateTime> RH_DATE { get; set; }
        public Nullable<int> CWCREW_ID { get; set; }
        public Nullable<int> CWSERV_ID { get; set; }
        public string H01A { get; set; }
        public string H01B { get; set; }
        public string H02A { get; set; }
        public string H02B { get; set; }
        public string H03A { get; set; }
        public string H03B { get; set; }
        public string H04A { get; set; }
        public string H04B { get; set; }
        public string H05A { get; set; }
        public string H05B { get; set; }
        public string H06A { get; set; }
        public string H06B { get; set; }
        public string H07A { get; set; }
        public string H07B { get; set; }
        public string H08A { get; set; }
        public string H08B { get; set; }
        public string H09A { get; set; }
        public string H09B { get; set; }
        public string H10A { get; set; }
        public string H10B { get; set; }
        public string H11A { get; set; }
        public string H11B { get; set; }
        public string H12A { get; set; }
        public string H12B { get; set; }
        public string H13A { get; set; }
        public string H13B { get; set; }
        public string H14A { get; set; }
        public string H14B { get; set; }
        public string H15A { get; set; }
        public string H15B { get; set; }
        public string H16A { get; set; }
        public string H16B { get; set; }
        public string H17A { get; set; }
        public string H17B { get; set; }
        public string H18A { get; set; }
        public string H18B { get; set; }
        public string H19A { get; set; }
        public string H19B { get; set; }
        public string H20A { get; set; }
        public string H20B { get; set; }
        public string H21A { get; set; }
        public string H21B { get; set; }
        public string H22A { get; set; }
        public string H22B { get; set; }
        public string H23A { get; set; }
        public string H23B { get; set; }
        public string H24A { get; set; }
        public string H24B { get; set; }
        public Nullable<short> FL_RSLTS { get; set; }
        public Nullable<short> FL_UPD { get; set; }
        public Nullable<short> FL_FLZD { get; set; }
        public string RH_RSLTS { get; set; }
        public string RH_NOTES { get; set; }
        public Nullable<double> REST_24 { get; set; }
        public Nullable<double> WRK_24 { get; set; }
        public Nullable<double> REST_IN24 { get; set; }
        public Nullable<double> REST_IN7D { get; set; }
        public Nullable<double> REST_IN3D { get; set; }
        public Nullable<short> RLS_NO { get; set; }
        public Nullable<short> FL_CHNG { get; set; }
        public Nullable<short> FL_SENT { get; set; }
        public Nullable<short> FL_REXST { get; set; }
        public Nullable<short> FL_DLT { get; set; }
        public Nullable<int> REST_PER_NUM { get; set; }
        public string RH_LOG { get; set; }
        public Nullable<int> VO_ID { get; set; }
        public Nullable<int> CS_ID { get; set; }
        public Nullable<short> FL_HIDE { get; set; }
        public string REPL_REMARKS { get; set; }
        public Nullable<short> FL_EWdate { get; set; }
        public Nullable<double> NONC_24 { get; set; }
        public Nullable<short> FL_EXCEPTION { get; set; }
        public Nullable<short> fl_excelption { get; set; }
    }
}
