//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BNFT_VSLEntities : DbContext
    {
        public BNFT_VSLEntities()
            : base("name=BNFT_VSLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CWCREW> CWCREWs { get; set; }
        public DbSet<CWCREWSERV> CWCREWSERVs { get; set; }
        public DbSet<CWPRANK> CWPRANKs { get; set; }
        public DbSet<CWRESTHR> CWRESTHRS { get; set; }
        public DbSet<VSL> VSLs { get; set; }
        public DbSet<VSL_FLAG> VSL_FLAG { get; set; }
    }
}
