//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSL
    {
        public int ID { get; set; }
        public string VSL_NAME { get; set; }
        public string TRN_NAME { get; set; }
        public string ABRV { get; set; }
        public string EX_NAME { get; set; }
        public Nullable<int> VSL_TYPE_ID { get; set; }
        public string VSL_YARD { get; set; }
        public string VSL_HULL_NO { get; set; }
        public string VSL_BLT { get; set; }
        public string VSL_KEEL { get; set; }
        public Nullable<double> VSL_DWT { get; set; }
        public Nullable<double> VSL_CROSS { get; set; }
        public Nullable<double> VSL_NATION_TONAG { get; set; }
        public Nullable<double> BEAM_M { get; set; }
        public Nullable<double> BEAM_F { get; set; }
        public Nullable<double> DPTH_M { get; set; }
        public Nullable<double> DPTH_F { get; set; }
        public Nullable<double> DRFT_M { get; set; }
        public Nullable<double> DRFT_F { get; set; }
        public Nullable<int> VSL_FLAG_ID { get; set; }
        public string PORT_REGISTR { get; set; }
        public string VSL_NOID { get; set; }
        public string IMO_NO { get; set; }
        public string MAIN_CLASS { get; set; }
        public string CLASS_NOTATON { get; set; }
        public string SIGNAL_LTRS { get; set; }
        public Nullable<double> SPD_LD { get; set; }
        public Nullable<double> SPD_BAL { get; set; }
        public Nullable<double> IFO_LD { get; set; }
        public Nullable<double> IFO_BAL { get; set; }
        public Nullable<double> IFO_PORT { get; set; }
        public Nullable<double> IFO_IDL { get; set; }
        public Nullable<double> IFO_HEAT { get; set; }
        public Nullable<double> DO_SEA_BAL { get; set; }
        public Nullable<double> DO_SEA { get; set; }
        public Nullable<double> DO_PORT { get; set; }
        public Nullable<double> DO_IDL { get; set; }
        public Nullable<double> LUB_ENG { get; set; }
        public Nullable<double> LUB_CYL { get; set; }
        public Nullable<double> LUB_DG { get; set; }
        public Nullable<double> LUB_TURBO { get; set; }
        public Nullable<double> CONS_WATER { get; set; }
        public Nullable<int> VSL_ENG_ID { get; set; }
        public string ENG_MODEL { get; set; }
        public string ENG_POWER { get; set; }
        public string VSL_OWN { get; set; }
        public string VSL_OWN_NO { get; set; }
        public string VSL_MNG { get; set; }
        public string VSL_MNG_NO { get; set; }
        public string VSL_MNG_ADR { get; set; }
        public string VSL_MNG_CITY { get; set; }
        public string VSL_MNG_ZIP { get; set; }
        public string VSL_MNG_CNTRY { get; set; }
        public string NOTE_DTL { get; set; }
        public string NOTE_REGISTR { get; set; }
        public string NOTE_SPD { get; set; }
        public string NOTE_ENG { get; set; }
        public string NOTE_SPC_DTLS { get; set; }
        public string NOTE_OWN { get; set; }
        public Nullable<short> FL_USE { get; set; }
        public Nullable<short> AA { get; set; }
        public string PREFIX { get; set; }
        public Nullable<double> ME_LD_CONS { get; set; }
        public Nullable<double> ME_BAL_CONS { get; set; }
        public Nullable<double> AUX_LD_FO_CONS { get; set; }
        public Nullable<double> AUX_BAL_FO_CONS { get; set; }
        public Nullable<double> AUX_LD_DO_CONS { get; set; }
        public Nullable<double> AUX_BAL_DO_CONS { get; set; }
        public string AUX_LD_FO_FTP { get; set; }
        public string AUX_BAL_FO_FTP { get; set; }
        public string AUX_LD_DO_FTP { get; set; }
        public string AUX_BAL_DO_FTP { get; set; }
        public string ME_LD_FTP { get; set; }
        public string ME_BAL_FTP { get; set; }
        public Nullable<double> VSL_LOA { get; set; }
        public Nullable<short> VSL_GEAR { get; set; }
        public Nullable<double> CUB_M { get; set; }
        public string CUB_M_UNIT { get; set; }
        public Nullable<short> FL_DSGN { get; set; }
        public Nullable<short> FL_USEFMC { get; set; }
        public Nullable<short> FL_PROP { get; set; }
        public Nullable<short> IMAGE_ID { get; set; }
        public Nullable<double> VSL_CAPACITY { get; set; }
        public Nullable<double> VSL_DRAFT { get; set; }
        public Nullable<double> VSL_TONS_RATE { get; set; }
        public Nullable<short> VSL_TONS_FL_INC_CM { get; set; }
        public Nullable<double> VSL_CONSTANT_WT { get; set; }
        public Nullable<double> VSL_FW { get; set; }
        public string VSL_CREW { get; set; }
        public string VSL_TELECOM { get; set; }
        public string VSL_DESCR_REP { get; set; }
        public Nullable<int> USERIN_ID { get; set; }
        public Nullable<System.DateTime> DATE_UPD { get; set; }
        public Nullable<int> USERUPD_ID { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
        public Nullable<System.DateTime> MNG_DATE_FRM { get; set; }
        public Nullable<System.DateTime> MNG_DATE_UP { get; set; }
        public Nullable<double> PRJ_RUNCOST { get; set; }
        public Nullable<double> MARKET_VALUE { get; set; }
        public Nullable<short> FL_TYPE { get; set; }
        public Nullable<double> LUB_ENG_CAPACITY { get; set; }
        public Nullable<double> LUB_CYL_CAPACITY { get; set; }
        public Nullable<double> LUB_DG_CAPACITY { get; set; }
        public Nullable<double> DG_FO_LD { get; set; }
        public Nullable<double> DG_FO_BAL { get; set; }
        public Nullable<int> acsite_id { get; set; }
        public Nullable<int> OLD_CWPENGINE_ID { get; set; }
        public Nullable<int> OLD_CWPVSLTYPE_ID { get; set; }
        public Nullable<int> OLD_CWPFLAG_ID { get; set; }
        public Nullable<int> VSL_DPT_ID { get; set; }
        public Nullable<int> VSL_RSP_ID { get; set; }
        public Nullable<int> VSL_LOC_ID { get; set; }
        public Nullable<short> FL_FORM_TYPE { get; set; }
        public Nullable<double> CAPACITY_BILGE { get; set; }
        public Nullable<double> CAPACITY_SLOP { get; set; }
        public Nullable<double> CAPACITY_SEWAGE { get; set; }
        public Nullable<double> IFO_TNK_LOAD_PORT { get; set; }
        public Nullable<double> IFO_TNK_DISH_PORT { get; set; }
        public string VSL_SIZE { get; set; }
        public Nullable<short> FL_CONTAINER { get; set; }
        public string IMO_PLACE { get; set; }
        public string IMO_PLACE_GR { get; set; }
        public string REG_NO { get; set; }
        public string VSL_ENGINE { get; set; }
        public string VSL_MNG_CNTRY_GR { get; set; }
    }
}
