//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSL_FLAG
    {
        public int ID { get; set; }
        public string DESCR { get; set; }
        public string ABRV { get; set; }
        public Nullable<short> AA { get; set; }
        public Nullable<short> FL_USE { get; set; }
        public string DESCR_GR { get; set; }
    }
}
