//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.FiltersCategories = new HashSet<FiltersCategory>();
            this.News = new HashSet<News>();
        }
    
        public string categoryName { get; set; }
        public int id { get; set; }
        public int webSiteId { get; set; }
    
        public virtual ICollection<FiltersCategory> FiltersCategories { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual WebSite WebSite { get; set; }
    }
}
