//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.FiltersCategories = new HashSet<FiltersCategories>();
            this.News = new HashSet<News>();
        }
    
        public string categoryName { get; set; }
        public int id { get; set; }
        public Nullable<int> webSiteId { get; set; }
        public int count { get; set; }
    
        public virtual ICollection<FiltersCategories> FiltersCategories { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual WebSites WebSites { get; set; }
    }
}
