//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiltersCategories
    {
        public int id { get; set; }
        public string filterText { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<short> symbolsCount { get; set; }
        public bool isSelected { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Users Users { get; set; }
    }
}
