//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livescores
    {
        public int id { get; set; }
        public string sport { get; set; }
        public string competition { get; set; }
        public string level { get; set; }
        public Nullable<int> usersId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
