//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> dateSaved { get; set; }
        public Nullable<int> articleId { get; set; }
        public int id { get; set; }
        public string href { get; set; }
        public Nullable<int> sourceWebSite { get; set; }
        public int categoryId { get; set; }
        public string keywords { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual WebSites WebSites { get; set; }
    }
}
