//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;    
    public partial class User
    {
        public User()
        {
            this.FiltersCategories = new HashSet<FiltersCategory>();
            this.Livescores = new HashSet<Livescore>();
            this.UsedEmails = new HashSet<UsedEmail>();
            this.UsersWebsites = new HashSet<UsersWebsite>();
        }
    
        public int id { get; set; }
        public string userName { get; set; }
        public string userEmail { get; set; }
        public bool isEnabled { get; set; }
        public string password { get; set; }
        public Nullable<short> sendNewsHour { get; set; }
        public bool convertCyrlicToLatin { get; set; }
        public Nullable<int> sizeLimit { get; set; }
        public short webSitesMaxNumber { get; set; }
    
        public virtual ICollection<FiltersCategory> FiltersCategories { get; set; }
        public virtual ICollection<Livescore> Livescores { get; set; }
        public virtual ICollection<UsedEmail> UsedEmails { get; set; }
        public virtual ICollection<UsersWebsite> UsersWebsites { get; set; }
    }
}
