//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSites
    {
        public WebSites()
        {
            this.Categories = new HashSet<Categories>();
            this.KeyWords = new HashSet<KeyWords>();
            this.News = new HashSet<News>();
            this.UsersWebsites = new HashSet<UsersWebsites>();
        }
    
        public int id { get; set; }
        public string siteName { get; set; }
        public string encoding { get; set; }
        public string domain { get; set; }
        public Nullable<System.DateTime> lastUpdated { get; set; }
    
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<KeyWords> KeyWords { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<UsersWebsites> UsersWebsites { get; set; }
    }
}
