//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsToEmailWebApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite
    {
        public WebSite()
        {
            this.Categories = new HashSet<Category>();
            this.KeyWords = new HashSet<KeyWord>();
            this.News = new HashSet<News>();
            this.UsersWebsites = new HashSet<UsersWebsite>();
        }
    
        public int id { get; set; }
        public string siteName { get; set; }
        public string encoding { get; set; }
        public string domain { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<KeyWord> KeyWords { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<UsersWebsite> UsersWebsites { get; set; }
    }
}
