//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBNFTExtract
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWRHSCHED
    {
        public int ID { get; set; }
        public Nullable<int> CWPRANK_ID { get; set; }
        public Nullable<short> FL_WK { get; set; }
    }
}
