//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBNFTExtract
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BNFT_VSLEntities : DbContext
    {
        public BNFT_VSLEntities()
            : base("name=BNFT_VSLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CWCREW> CWCREW { get; set; }
        public virtual DbSet<CWCREWSERV> CWCREWSERV { get; set; }
        public virtual DbSet<CWPRANK> CWPRANK { get; set; }
        public virtual DbSet<CWRESTHRS> CWRESTHRS { get; set; }
        public virtual DbSet<CWRHSCHED> CWRHSCHED { get; set; }
        public virtual DbSet<SQEVENT_HST> SQEVENT_HST { get; set; }
        public virtual DbSet<SQEVENT_HST_PARTIC> SQEVENT_HST_PARTIC { get; set; }
        public virtual DbSet<VSL> VSL { get; set; }
        public virtual DbSet<VSL_FLAG> VSL_FLAG { get; set; }
        public virtual DbSet<PFINT_DATELINE> PFINT_DATELINE { get; set; }
    }
}
