//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBNFTExtract
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFINT_DATELINE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DATE_LINE { get; set; }
        public string FL_EW { get; set; }
        public Nullable<int> VSL_ID { get; set; }
        public Nullable<int> USERIN_ID { get; set; }
        public Nullable<int> USERUPD_ID { get; set; }
        public Nullable<short> FL_DATELINE { get; set; }
        public Nullable<System.DateTime> DATE_IN { get; set; }
        public Nullable<System.DateTime> DATE_UPD { get; set; }
        public Nullable<int> CS_ID { get; set; }
        public Nullable<int> VO_ID { get; set; }
        public Nullable<short> FL_CHNG { get; set; }
        public Nullable<short> FL_SENT { get; set; }
        public Nullable<short> RLS_NO { get; set; }
        public Nullable<short> FL_DLT { get; set; }
        public Nullable<short> FL_REXST { get; set; }
    }
}
