//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBNFTExtract
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQEVENT_HST
    {
        public int ID { get; set; }
        public string EVT_NOTES { get; set; }
        public Nullable<int> SQEVENT_HST_ID { get; set; }
        public Nullable<System.DateTime> EVENT_DT { get; set; }
    }
}
