//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BFDL
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    public partial class Betlines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Betlines()
        {
            this.PlacedBets = new HashSet<PlacedBets>();
        }
    
        public int BetlineId { get; set; }
        public double stakeRangeMin { get; set; }
        public double stakeRangeMax { get; set; }
        public double initialProfitPerBet { get; set; }
        public double profitPerBet { get; set; }
        public bool lastBetLost { get; set; }
        public bool isActive { get; set; }
        public string currencyCode { get; set; }
        public Nullable<int> Filter_FilterId { get; set; }
        public string lastPlacedBetId { get; set; }
        public string algorithmName { get; set; }
        public string betType { get; set; }
        public string ownersUserName { get; set; }
        public string betlineName { get; set; }
        public double profitPerBudjet { get; set; }
        public decimal ballance { get; set; }
    
        public virtual Filters Filters { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlacedBets> PlacedBets { get; set; }

        public virtual ICollection<PlacedBets> PlacedBetsRunning
        {
            get
            {
                var hrsb4r3 = DateTime.Now.AddHours(-24);
                return this.PlacedBets.Where(b => b.datePlaced > hrsb4r3).ToList();
            }
        }
    }
}
