//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reviseDatabases
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlacedBet
    {
        public long betId { get; set; }
        public string resultCode { get; set; }
        public bool success { get; set; }
        public System.DateTime datePlaced { get; set; }
        public int marketId { get; set; }
        public string marketMenuPath { get; set; }
        public double averagePrice { get; set; }
        public string Selection { get; set; }
        public Nullable<System.DateTime> dateSettled { get; set; }
        public string score { get; set; }
        public Nullable<int> sortedOrder { get; set; }
        public string marketName { get; set; }
        public Nullable<int> eventType { get; set; }
    }
}
