//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Betlines = new HashSet<Betline>();
        }
    
        public string userName { get; set; }
        public string Password { get; set; }
        public bool isActive { get; set; }
        public string appKey { get; set; }
        public string certFileName { get; set; }
    
        public virtual ICollection<Betline> Betlines { get; set; }
    }
}
