//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string LastName { get; set; }
        public string PersonalIdNumber { get; set; }
        public string TypeID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Sex { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDateUpdate { get; set; }
        public string ClinicalDisorders { get; set; }
        public string Image { get; set; }
        public string C11 { get; set; }
        public string C12 { get; set; }
        public string C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public string C16 { get; set; }
        public string C17 { get; set; }
        public string C18 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public string C23 { get; set; }
        public string C24 { get; set; }
        public string C25 { get; set; }
        public string C26 { get; set; }
        public string C27 { get; set; }
        public string C28 { get; set; }
        public string C31 { get; set; }
        public string C32 { get; set; }
        public string C33 { get; set; }
        public string C34 { get; set; }
        public string C35 { get; set; }
        public string C36 { get; set; }
        public string C37 { get; set; }
        public string C38 { get; set; }
        public string C41 { get; set; }
        public string C42 { get; set; }
        public string C43 { get; set; }
        public string C44 { get; set; }
        public string C45 { get; set; }
        public string C46 { get; set; }
        public string C47 { get; set; }
        public string C48 { get; set; }
        public bool C51 { get; set; }
        public bool C52 { get; set; }
        public bool C53 { get; set; }
        public bool C54 { get; set; }
        public bool C55 { get; set; }
        public bool C61 { get; set; }
        public bool C62 { get; set; }
        public bool C63 { get; set; }
        public bool C64 { get; set; }
        public bool C65 { get; set; }
        public bool C71 { get; set; }
        public bool C72 { get; set; }
        public bool C73 { get; set; }
        public bool C74 { get; set; }
        public bool C75 { get; set; }
        public bool C81 { get; set; }
        public bool C82 { get; set; }
        public bool C83 { get; set; }
        public bool C84 { get; set; }
        public bool C85 { get; set; }
        public string Notes { get; set; }
    }
}
