//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsCashPayment { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public string Currency { get; set; }
        
        public bool IsDeleted { get; set; }
    }
}
