//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public byte ToothCode { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public string Diagnose { get; set; }
        public Nullable<double> Price { get; set; }
        public string Image { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<double> PriceNOI { get; set; }
        public Nullable<double> PriceDT { get; set; }
        public bool IsDeleted { get; set; }
        public bool PaidByCard { get; set; }
        public bool PaidCash { get; set; }
    }
}
