//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaradTestDBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public Questions()
        {
            this.Statistics = new HashSet<Statistics>();
        }
    
        public int Id { get; set; }
        public string answers { get; set; }
        public string questionText { get; set; }
        public byte[] questionImage { get; set; }
        public string correctAnswer { get; set; }
        public string category { get; set; }
        public string level { get; set; }
        public string competency { get; set; }
    
        public virtual ICollection<Statistics> Statistics { get; set; }
    }
}
