//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaradTestDBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public int userId { get; set; }
        public int questionId { get; set; }
        public Nullable<int> answeredTotal { get; set; }
        public Nullable<int> answeredCorrect { get; set; }
    
        public virtual Questions Questions { get; set; }
        public virtual Users Users { get; set; }
    }
}
