//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBLBettingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public Filter()
        {
            this.Betlines = new HashSet<Betline>();
        }
    
        public int FilterId { get; set; }
        public Nullable<System.DateTime> marketTimeFrom { get; set; }
        public Nullable<System.DateTime> marketTimeTo { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<double> totalAmountMatchedMin { get; set; }
        public Nullable<double> totalAmountMatchedMax { get; set; }
        public string marketNames { get; set; }
        public string sortedOrders { get; set; }
        public Nullable<byte> maxBetsCount { get; set; }
        public Nullable<double> maxAmmountIncremented { get; set; }
        public double maxAmmountIncrementedPerBudjet { get; set; }
        public Nullable<short> goalDifferenceMin { get; set; }
        public Nullable<short> goalDifferenceMax { get; set; }
        public string textQuery { get; set; }
        public string exchangeIds { get; set; }
        public string eventTypeIds { get; set; }
        public string compeitionIds { get; set; }
        public string marketIds { get; set; }
        public string venues { get; set; }
        public Nullable<bool> bspOnly { get; set; }
        public Nullable<bool> inPlayOnly { get; set; }
        public string marketBettingTypes { get; set; }
        public string marketCountries { get; set; }
        public string withOrders { get; set; }
    
        public virtual ICollection<Betline> Betlines { get; set; }
    }
}
